#!/bin/sh

NAME=cameraServer
PIDFILE=/var/run/$NAME.pid
CMD=/home/user/runCamera.sh


start() {
	printf "Starting $NAME: "
	start-stop-daemon -S -q -m -b -p $PIDFILE --exec $CMD
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping $NAME: "
	start-stop-daemon -K -q -s 2 -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
